import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import { Button } from "../ui/button";
import { Input } from "../ui/input";
import { Textarea } from "../ui/textarea";
import { Label } from "../ui/label";
import { Badge } from "../ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "../ui/avatar";
import { Heart, Star, Settings, Mail, Bell, Check, X, Plus, Minus } from "lucide-react";
export function AtomShowcase({ componentName }) {
    const renderComponent = () => {
        switch (componentName) {
            case "Button":
                return (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex flex-wrap gap-3", children: [_jsx(Button, { className: "bg-violet-500 hover:bg-violet-600 text-white", children: "Primary" }), _jsx(Button, { className: "bg-slate-700 hover:bg-slate-600 text-white", children: "Secondary" }), _jsx(Button, { variant: "outline", className: "border-slate-600 text-slate-300 hover:bg-slate-800", children: "Outline" }), _jsx(Button, { className: "bg-transparent hover:bg-slate-800 text-slate-300", children: "Ghost" })] }), _jsxs("div", { className: "flex flex-wrap gap-3", children: [_jsx(Button, { className: "bg-emerald-500 hover:bg-emerald-600 text-white", children: "Success" }), _jsx(Button, { className: "bg-amber-500 hover:bg-amber-600 text-white", children: "Warning" }), _jsx(Button, { className: "bg-rose-500 hover:bg-rose-600 text-white", children: "Destructive" })] })] }));
            case "IconButton":
                return (_jsxs("div", { className: "flex flex-wrap gap-3", children: [_jsx(Button, { size: "icon", className: "bg-violet-500 hover:bg-violet-600 text-white rounded-lg", children: _jsx(Heart, { size: 18 }) }), _jsx(Button, { size: "icon", className: "bg-slate-700 hover:bg-slate-600 text-white rounded-full", children: _jsx(Settings, { size: 18 }) }), _jsx(Button, { size: "icon", className: "bg-emerald-500 hover:bg-emerald-600 text-white rounded-xl", children: _jsx(Plus, { size: 18 }) }), _jsx(Button, { size: "icon", className: "bg-rose-500 hover:bg-rose-600 text-white rounded-lg", children: _jsx(X, { size: 18 }) })] }));
            case "GhostButton":
                return (_jsxs("div", { className: "flex flex-wrap gap-3", children: [_jsx(Button, { className: "bg-transparent hover:bg-violet-500/10 text-violet-400 border border-violet-500/30", children: "Ghost Violet" }), _jsx(Button, { className: "bg-transparent hover:bg-emerald-500/10 text-emerald-400 border border-emerald-500/30", children: "Ghost Green" }), _jsx(Button, { className: "bg-transparent hover:bg-rose-500/10 text-rose-400 border border-rose-500/30", children: "Ghost Red" })] }));
            case "Pill":
                return (_jsxs("div", { className: "flex flex-wrap gap-3", children: [_jsx("span", { className: "px-4 py-1.5 rounded-full bg-violet-500 text-white text-sm", children: "Active" }), _jsx("span", { className: "px-4 py-1.5 rounded-full bg-slate-700 text-slate-300 text-sm", children: "Inactive" }), _jsx("span", { className: "px-4 py-1.5 rounded-full bg-emerald-500/20 text-emerald-400 text-sm border border-emerald-500/30", children: "Success" }), _jsx("span", { className: "px-4 py-1.5 rounded-full bg-amber-500/20 text-amber-400 text-sm border border-amber-500/30", children: "Warning" })] }));
            case "Input":
                return (_jsxs("div", { className: "space-y-4 max-w-md", children: [_jsxs("div", { className: "space-y-2", children: [_jsx(Label, { className: "text-slate-300", children: "Default Input" }), _jsx(Input, { placeholder: "Enter text...", className: "bg-slate-800 border-slate-700 text-white" })] }), _jsxs("div", { className: "space-y-2", children: [_jsx(Label, { className: "text-slate-300", children: "With Icon" }), _jsxs("div", { className: "relative", children: [_jsx(Mail, { className: "absolute left-3 top-1/2 -translate-y-1/2 text-slate-500", size: 16 }), _jsx(Input, { placeholder: "Email address", className: "pl-10 bg-slate-800 border-slate-700 text-white" })] })] }), _jsxs("div", { className: "space-y-2", children: [_jsx(Label, { className: "text-slate-300", children: "Disabled" }), _jsx(Input, { placeholder: "Disabled input", disabled: true, className: "bg-slate-800 border-slate-700 text-slate-500 opacity-50" })] })] }));
            case "Textarea":
                return (_jsx("div", { className: "space-y-4 max-w-md", children: _jsxs("div", { className: "space-y-2", children: [_jsx(Label, { className: "text-slate-300", children: "Default Textarea" }), _jsx(Textarea, { placeholder: "Enter your message...", className: "bg-slate-800 border-slate-700 text-white min-h-24" })] }) }));
            case "Checkbox":
                return (_jsxs("div", { className: "space-y-3", children: [_jsxs("label", { className: "flex items-center gap-3 cursor-pointer", children: [_jsx("div", { className: "w-5 h-5 rounded border-2 border-slate-600 bg-slate-800 flex items-center justify-center", children: _jsx(Check, { size: 14, className: "text-violet-500" }) }), _jsx("span", { className: "text-slate-300", children: "Checked option" })] }), _jsxs("label", { className: "flex items-center gap-3 cursor-pointer", children: [_jsx("div", { className: "w-5 h-5 rounded border-2 border-slate-600 bg-slate-800" }), _jsx("span", { className: "text-slate-300", children: "Unchecked option" })] })] }));
            case "Radio":
                return (_jsxs("div", { className: "space-y-3", children: [_jsxs("label", { className: "flex items-center gap-3 cursor-pointer", children: [_jsx("div", { className: "w-5 h-5 rounded-full border-2 border-violet-500 bg-slate-800 flex items-center justify-center", children: _jsx("div", { className: "w-2.5 h-2.5 rounded-full bg-violet-500" }) }), _jsx("span", { className: "text-slate-300", children: "Option A" })] }), _jsxs("label", { className: "flex items-center gap-3 cursor-pointer", children: [_jsx("div", { className: "w-5 h-5 rounded-full border-2 border-slate-600 bg-slate-800" }), _jsx("span", { className: "text-slate-300", children: "Option B" })] })] }));
            case "Switch":
                return (_jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-11 h-6 rounded-full bg-violet-500 relative cursor-pointer", children: _jsx("div", { className: "absolute right-0.5 top-0.5 w-5 h-5 rounded-full bg-white shadow" }) }), _jsx("span", { className: "text-slate-300", children: "Enabled" })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-11 h-6 rounded-full bg-slate-700 relative cursor-pointer", children: _jsx("div", { className: "absolute left-0.5 top-0.5 w-5 h-5 rounded-full bg-slate-400 shadow" }) }), _jsx("span", { className: "text-slate-300", children: "Disabled" })] })] }));
            case "Badge":
                return (_jsxs("div", { className: "flex flex-wrap gap-3", children: [_jsx(Badge, { className: "bg-slate-700 text-slate-300", children: "Default" }), _jsx(Badge, { className: "bg-violet-500 text-white", children: "Primary" }), _jsx(Badge, { className: "bg-emerald-500/20 text-emerald-400 border border-emerald-500/30", children: "Success" }), _jsx(Badge, { className: "bg-amber-500/20 text-amber-400 border border-amber-500/30", children: "Warning" }), _jsx(Badge, { className: "bg-rose-500/20 text-rose-400 border border-rose-500/30", children: "Error" })] }));
            case "Tag":
                return (_jsxs("div", { className: "flex flex-wrap gap-2", children: [_jsxs("span", { className: "px-3 py-1 rounded-lg bg-slate-800 text-slate-300 text-sm border border-slate-700 flex items-center gap-1", children: ["React ", _jsx(X, { size: 12, className: "cursor-pointer hover:text-rose-400" })] }), _jsxs("span", { className: "px-3 py-1 rounded-lg bg-slate-800 text-slate-300 text-sm border border-slate-700 flex items-center gap-1", children: ["TypeScript ", _jsx(X, { size: 12, className: "cursor-pointer hover:text-rose-400" })] }), _jsxs("span", { className: "px-3 py-1 rounded-lg bg-slate-800 text-slate-300 text-sm border border-slate-700 flex items-center gap-1", children: ["Tailwind ", _jsx(X, { size: 12, className: "cursor-pointer hover:text-rose-400" })] })] }));
            case "Chip":
                return (_jsxs("div", { className: "flex flex-wrap gap-2", children: [_jsx("span", { className: "px-3 py-1 rounded-full bg-violet-500/20 text-violet-400 text-sm border border-violet-500/30", children: "Featured" }), _jsx("span", { className: "px-3 py-1 rounded-full bg-emerald-500/20 text-emerald-400 text-sm border border-emerald-500/30", children: "New" }), _jsx("span", { className: "px-3 py-1 rounded-full bg-amber-500/20 text-amber-400 text-sm border border-amber-500/30", children: "Popular" })] }));
            case "Avatar":
                return (_jsxs("div", { className: "flex items-center gap-4", children: [_jsxs(Avatar, { className: "w-8 h-8 border-2 border-violet-500", children: [_jsx(AvatarImage, { src: "" }), _jsx(AvatarFallback, { className: "bg-violet-500 text-white text-xs", children: "SM" })] }), _jsxs(Avatar, { className: "w-10 h-10 border-2 border-emerald-500", children: [_jsx(AvatarImage, { src: "" }), _jsx(AvatarFallback, { className: "bg-emerald-500 text-white text-sm", children: "MD" })] }), _jsxs(Avatar, { className: "w-12 h-12 border-2 border-amber-500", children: [_jsx(AvatarImage, { src: "" }), _jsx(AvatarFallback, { className: "bg-amber-500 text-white text-base", children: "LG" })] }), _jsxs(Avatar, { className: "w-16 h-16 border-2 border-rose-500", children: [_jsx(AvatarImage, { src: "" }), _jsx(AvatarFallback, { className: "bg-rose-500 text-white text-lg", children: "XL" })] })] }));
            case "StatusDot":
                return (_jsxs("div", { className: "flex items-center gap-6", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-2.5 h-2.5 rounded-full bg-emerald-500" }), _jsx("span", { className: "text-slate-300 text-sm", children: "Online" })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-2.5 h-2.5 rounded-full bg-amber-500" }), _jsx("span", { className: "text-slate-300 text-sm", children: "Away" })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-2.5 h-2.5 rounded-full bg-rose-500" }), _jsx("span", { className: "text-slate-300 text-sm", children: "Offline" })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-2.5 h-2.5 rounded-full bg-slate-500" }), _jsx("span", { className: "text-slate-300 text-sm", children: "Busy" })] })] }));
            case "Spinner":
                return (_jsxs("div", { className: "flex items-center gap-6", children: [_jsx("div", { className: "w-5 h-5 border-2 border-violet-500 border-t-transparent rounded-full animate-spin" }), _jsx("div", { className: "w-8 h-8 border-3 border-emerald-500 border-t-transparent rounded-full animate-spin" }), _jsx("div", { className: "w-10 h-10 border-4 border-amber-500 border-t-transparent rounded-full animate-spin" })] }));
            case "ProgressBar":
                return (_jsxs("div", { className: "space-y-4 w-64", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex justify-between text-sm mb-1", children: [_jsx("span", { className: "text-slate-400", children: "Progress" }), _jsx("span", { className: "text-violet-400", children: "25%" })] }), _jsx("div", { className: "h-2 bg-slate-800 rounded-full overflow-hidden", children: _jsx("div", { className: "h-full w-1/4 bg-violet-500 rounded-full" }) })] }), _jsxs("div", { children: [_jsxs("div", { className: "flex justify-between text-sm mb-1", children: [_jsx("span", { className: "text-slate-400", children: "Progress" }), _jsx("span", { className: "text-emerald-400", children: "75%" })] }), _jsx("div", { className: "h-2 bg-slate-800 rounded-full overflow-hidden", children: _jsx("div", { className: "h-full w-3/4 bg-emerald-500 rounded-full" }) })] })] }));
            case "Heading":
                return (_jsxs("div", { className: "space-y-2", children: [_jsx("h1", { className: "text-4xl font-bold text-white", children: "Heading 1" }), _jsx("h2", { className: "text-3xl font-bold text-white", children: "Heading 2" }), _jsx("h3", { className: "text-2xl font-semibold text-white", children: "Heading 3" }), _jsx("h4", { className: "text-xl font-semibold text-white", children: "Heading 4" }), _jsx("h5", { className: "text-lg font-medium text-white", children: "Heading 5" }), _jsx("h6", { className: "text-base font-medium text-white", children: "Heading 6" })] }));
            case "Code":
                return (_jsx("code", { className: "px-2 py-1 rounded bg-slate-800 text-violet-400 font-mono text-sm border border-slate-700", children: "const x = 42;" }));
            case "Kbd":
                return (_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("kbd", { className: "px-2 py-1 rounded bg-slate-800 text-slate-300 font-mono text-xs border border-slate-700 shadow", children: "Ctrl" }), _jsx("span", { className: "text-slate-500", children: "+" }), _jsx("kbd", { className: "px-2 py-1 rounded bg-slate-800 text-slate-300 font-mono text-xs border border-slate-700 shadow", children: "C" })] }));
            default:
                return (_jsx("div", { className: "text-slate-400", children: "Select a component to see its variants" }));
        }
    };
    return (_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, className: "bg-slate-900 rounded-2xl border border-slate-800 p-6", children: [_jsxs("div", { className: "flex items-center justify-between mb-6", children: [_jsxs("h3", { className: "text-white font-semibold text-lg", children: [componentName, " Component"] }), _jsx(Badge, { className: "bg-rose-500/20 text-rose-400 border border-rose-500/30", children: "Atom" })] }), _jsx("div", { className: "bg-slate-950 rounded-xl p-6 border border-slate-800", children: renderComponent() }), _jsx("div", { className: "mt-4 p-4 bg-slate-800/50 rounded-xl", children: _jsxs("p", { className: "text-slate-400 text-sm", children: [_jsx("span", { className: "text-violet-400 font-medium", children: "Golden Rule:" }), " Atoms contain no business logic. They are pure UI primitives that can be reused across the entire application."] }) })] }));
}
//# sourceMappingURL=AtomShowcase.js.map